package com.hetaozs.tory.util;

/**
 * Some consts used in processors
 *
 * @author Alex <a href="mailto:zhilong.liu@aliyun.com">Contact me.</a>
 * @version 1.0
 * @since 16/8/24 20:18
 */
public class Consts {
    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "MRouter";
    public static final String TAG = PROJECT + "::";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MROUTER.";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String METHOD_INJECT = "inject";
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root";
    public static final String NAME_OF_PROVIDER = PROJECT + SEPARATOR + "Providers";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Group" + SEPARATOR;
    public static final String NAME_OF_INTERCEPTOR = PROJECT + SEPARATOR + "Interceptors";
    public static final String NAME_OF_AUTOWIRED = SEPARATOR + PROJECT + SEPARATOR + "Autowired";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String SERVICE = "android.app.Service";
    public static final String PARCELABLE = "android.os.Parcelable";

    // Java type
    private static final String LANG = "java.lang";
    public static final String BYTE = LANG + ".Byte";
    public static final String SHORT = LANG + ".Short";
    public static final String INTEGER = LANG + ".Integer";
    public static final String LONG = LANG + ".Long";
    public static final String FLOAT = LANG + ".Float";
    public static final String DOUBEL = LANG + ".Double";
    public static final String BOOLEAN = LANG + ".Boolean";
    public static final String STRING = LANG + ".String";

    // Custom interface
    public static final String MROUTER_PACKAGE = "com.hetaozs.tory.mrouter";
    private static final String TEMPLATE_PACKAGE = ".template";
    private static final String ANNOTATION_PACKAGE = ".annotation";
    public static final String ISYRINGE =  MROUTER_PACKAGE + TEMPLATE_PACKAGE+ ".ISyringe";


    // Log
    static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";

    // Options of processor
    public static final String KEY_MODULE_NAME = "moduleName";

    private static final String AROUTER_FACADE_PACKAGE = "com.alibaba.android.arouter.facade";
    // Annotation type
    public static final String AROUTER_ANNOTATION_TYPE_AUTOWIRED = AROUTER_FACADE_PACKAGE + ".annotation.Autowired";
    public static final String AROUTER_ANNOTATION_TYPE_ROUTE = AROUTER_FACADE_PACKAGE + ".annotation.Route";

    public static final String MROUTER_ANNOTATION_TYPE_AUTOWIRED = MROUTER_PACKAGE + ANNOTATION_PACKAGE + ".MAutowired";
}